-- ~/.config/nvim/lua/plugins/init.lua
-- Each plugin is defined in a separate file under this folder

return {
  require("plugins.editorconfig"),
  require("plugins.ts-autotag"),
  require("plugins.indentwise"),
  require("plugins.inlayhints"),
  require("plugins.cmp-under-comparator"),
  require("plugins.notify"),
  require("plugins.phpcsf"),
  require("plugins.indent-blankline"),
  require("plugins.spectre"),
  require("plugins.markdown-preview"),
  require("plugins.smartcolumn"),
  require("plugins.visual-whitespace"),
  require("plugins.telescope"),
  require("plugins.theme"),
  require("plugins.lsp-zero"),
  require("plugins.treesitter"),
  require("plugins.harpoon"),
  require("plugins.undotree"),
  require("plugins.fugitive"),
  require("plugins.nvim-tree"),
  require("plugins.web-devicons"),
  require("plugins.codeium"),
  require("plugins.actions-preview"),
  require("plugins.sttusline"),
  require("plugins.visual-multi"),
  require("plugins.hop"),
  require("plugins.comment"),
  require("plugins.git-blame"),
  require("plugins.barbar"),
  require("plugins.rust"),
  require("plugins.surround"),
  require("plugins.colorizer"),
}
